### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by xiaomuahua666** [lihongxun945/gobang#56]
能否说说在自己的ubuntu服务器中，如何安装这个项目。
**
![image](https://github.com/lihongxun945/gobang/assets/109423710/e7209c2c-fbae-4e3a-8af3-a472e4023f4c)
**
我按照gpt给的提示，一直无法go build

![image](https://github.com/lihongxun945/gobang/assets/109423710/a4b830f9-9223-49e7-ab3b-4bb6fa9bbe43)

**Comment by xiaomuahua666** [comment]
好像明白了

**Comment by xiaomuahua666** [comment]
Error: Failed to initialize watch plugin "node_modules/jest-watch-typeahead/filename.js":

  ● Test suite failed to run

    /root/gobang/node_modules/jest-watch-typeahead/filename.js:1
    export { default } from './build/file_name_plugin/plugin.js';
    ^^^^^^

    SyntaxError: Unexpected token export

      at requireOrImportModule (node_modules/@jest/core/node_modules/jest-util/build/requireOrImportModule.js:53:28)
      at watch (node_modules/@jest/core/build/watch.js:337:78)
      at runWatch (node_modules/@jest/core/build/cli/index.js:359:29)

npm ERR! Test failed.  See above for more details.


用npm试过了，仍然报错:(
